#### Data Manipulation and Analysis with Pandas

Data Manipulation and analysis are the tasks in any data science or data analysis project. pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, trnasform and extract insights from data. in this lesson,  we will cover various data manipulation and analysis techniques using pandas.

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('customer.csv')
## fetch the first 5 rows
df.head(5)

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [6]:
## last 5
df.tail(5)

      Make Colour  Odometer (KM)  Doors    Price
44  Toyota   Blue       213893.0    4.0   5743.0
45  Nissan   Blue       231057.0    4.0   5925.0
46  Toyota  White       100938.0    4.0  25196.0
47  Toyota   Blue       243969.0    NaN  16138.0
48  Nissan  White       107096.0    3.0   6075.0

In [7]:
df.describe()

       Odometer (KM)      Doors         Price
count      47.000000  47.000000     49.000000
mean   133329.851064   3.936170  15002.612245
std     61080.847138   0.384722   7358.296618
min     17119.000000   3.000000   5743.000000
25%     90728.000000   4.000000   9109.000000
50%    134181.000000   4.000000  14274.000000
75%    185393.000000   4.000000  19943.000000
max    243969.000000   5.000000  34465.000000

In [8]:
df.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [9]:
## also check missing value --> true
[df.isnull().any()]

[Make              True
 Colour            True
 Odometer (KM)     True
 Doors             True
 Price            False
 dtype: bool]

In [10]:
## Handling missing value
df.isnull().sum()

Make             3
Colour           2
Odometer (KM)    2
Doors            2
Price            0
dtype: int64

In [11]:
df_filled=df.fillna(0)

In [9]:
## Filling missing values with the mean of the column
df['Numb_doors']=df['Doors'].fillna(df['Doors'].mode())
df

      Make Colour  Odometer (KM)  Doors    Price  Numb_doors
0    Honda  White        35431.0    4.0  15323.0         4.0
1      BMW   Blue       192714.0    5.0  19943.0         5.0
2    Honda  White        84714.0    4.0  28343.0         4.0
3   Toyota  White       154365.0    4.0  13434.0         4.0
4   Nissan   Blue       181577.0    3.0  14043.0         3.0
5    Honda    Red        42652.0    4.0  23883.0         4.0
6   Toyota   Blue       163453.0    4.0   8473.0         4.0
7    Honda  White            NaN    4.0  20306.0         4.0
8      NaN  White       130538.0    4.0   9374.0         4.0
9    Honda   Blue        51029.0    4.0  26683.0         4.0
10  Nissan  White       167421.0    4.0  16259.0         4.0
11  Nissan  Green        17119.0    4.0   6160.0         4.0
12  Nissan  White       102303.0    4.0  16909.0         4.0
13     NaN  White       134181.0    4.0  11121.0         4.0
14   Honda   Blue       199833.0    4.0  18946.0         4.0
15  Toyota   Blue       205592.0    4.0  16290.0         4.0
16  Toyota    Red        96742.0    4.0  34465.0         4.0
17     BMW  White       194189.0    5.0  17177.0         5.0
18  Nissan  White        67991.0    3.0   9109.0         3.0
19  Nissan   Blue       215820.0    4.0   6010.0         4.0
20  Toyota    NaN       124844.0    4.0  24130.0         4.0
21   Honda    NaN        30615.0    4.0  29653.0         4.0
22  Toyota  White       148744.0    4.0  22489.0         4.0
23   Honda  Green       130075.0    4.0  21242.0         4.0
24   Honda   Blue       172718.0    4.0  14274.0         4.0
25   Honda   Blue       125819.0    4.0  15686.0         4.0
26   Honda  White       180390.0    4.0  13344.0         4.0
27   Honda  Green        82783.0    4.0  10984.0         4.0
28   Honda  White        56687.0    4.0   6135.0         4.0
29  Toyota  White       112004.0    4.0  13586.0         4.0
30  Nissan   Blue        34024.0    4.0  23929.0         4.0
31  Toyota  White       108569.0    NaN   6866.0         NaN
32  Nissan  White       203795.0    4.0   9330.0         4.0
33  Nissan  Green       153554.0    3.0   9780.0         3.0
34   Honda   Blue        71949.0    4.0  17516.0         4.0
35   Honda   Blue       191622.0    4.0   8738.0         4.0
36  Nissan   Blue        38186.0    4.0  23438.0         4.0
37  Nissan  White            NaN    4.0  15131.0         4.0
38  Nissan   Blue       146430.0    3.0   9224.0         3.0
39  Toyota  Green       109868.0    4.0   6574.0         4.0
40     NaN  White       177894.0    4.0   9229.0         4.0
41  Toyota   Blue       189209.0    4.0   7100.0         4.0
42   Honda  Black       200490.0    4.0   6337.0         4.0
43  Toyota   Blue       141617.0    4.0  19085.0         4.0
44  Toyota   Blue       213893.0    4.0   5743.0         4.0
45  Nissan   Blue       231057.0    4.0   5925.0         4.0
46  Toyota  White       100938.0    4.0  25196.0         4.0
47  Toyota   Blue       243969.0    NaN  16138.0         NaN
48  Nissan  White       107096.0    3.0   6075.0         3.0

In [12]:
## if want to change data type 
df.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [13]:
## Renaming columns
df= df.rename(columns={'Doors':'numb_doors'})  ## keyvalue pairs
df.head()

     Make Colour  Odometer (KM)  numb_doors    Price
0   Honda  White        35431.0         4.0  15323.0
1     BMW   Blue       192714.0         5.0  19943.0
2   Honda  White        84714.0         4.0  28343.0
3  Toyota  White       154365.0         4.0  13434.0
4  Nissan   Blue       181577.0         3.0  14043.0

In [15]:
# change datatypes
## fill NaN values with the column mode and convert to string
df['numb_doors'] = df['numb_doors'].fillna(df['numb_doors'].mode()[0]).astype(str)  ## or df['Mix_colour']=df['Colour'].fillna(df['Colour'].mode()[0]).astype(str)
df.head()

     Make Colour  Odometer (KM) numb_doors    Price
0   Honda  White        35431.0        4.0  15323.0
1     BMW   Blue       192714.0        5.0  19943.0
2   Honda  White        84714.0        4.0  28343.0
3  Toyota  White       154365.0        4.0  13434.0
4  Nissan   Blue       181577.0        3.0  14043.0

In [16]:
df

      Make Colour  Odometer (KM) numb_doors    Price
0    Honda  White        35431.0        4.0  15323.0
1      BMW   Blue       192714.0        5.0  19943.0
2    Honda  White        84714.0        4.0  28343.0
3   Toyota  White       154365.0        4.0  13434.0
4   Nissan   Blue       181577.0        3.0  14043.0
5    Honda    Red        42652.0        4.0  23883.0
6   Toyota   Blue       163453.0        4.0   8473.0
7    Honda  White            NaN        4.0  20306.0
8      NaN  White       130538.0        4.0   9374.0
9    Honda   Blue        51029.0        4.0  26683.0
10  Nissan  White       167421.0        4.0  16259.0
11  Nissan  Green        17119.0        4.0   6160.0
12  Nissan  White       102303.0        4.0  16909.0
13     NaN  White       134181.0        4.0  11121.0
14   Honda   Blue       199833.0        4.0  18946.0
15  Toyota   Blue       205592.0        4.0  16290.0
16  Toyota    Red        96742.0        4.0  34465.0
17     BMW  White       194189.0        5.0  17177.0
18  Nissan  White        67991.0        3.0   9109.0
19  Nissan   Blue       215820.0        4.0   6010.0
20  Toyota    NaN       124844.0        4.0  24130.0
21   Honda    NaN        30615.0        4.0  29653.0
22  Toyota  White       148744.0        4.0  22489.0
23   Honda  Green       130075.0        4.0  21242.0
24   Honda   Blue       172718.0        4.0  14274.0
25   Honda   Blue       125819.0        4.0  15686.0
26   Honda  White       180390.0        4.0  13344.0
27   Honda  Green        82783.0        4.0  10984.0
28   Honda  White        56687.0        4.0   6135.0
29  Toyota  White       112004.0        4.0  13586.0
30  Nissan   Blue        34024.0        4.0  23929.0
31  Toyota  White       108569.0        4.0   6866.0
32  Nissan  White       203795.0        4.0   9330.0
33  Nissan  Green       153554.0        3.0   9780.0
34   Honda   Blue        71949.0        4.0  17516.0
35   Honda   Blue       191622.0        4.0   8738.0
36  Nissan   Blue        38186.0        4.0  23438.0
37  Nissan  White            NaN        4.0  15131.0
38  Nissan   Blue       146430.0        3.0   9224.0
39  Toyota  Green       109868.0        4.0   6574.0
40     NaN  White       177894.0        4.0   9229.0
41  Toyota   Blue       189209.0        4.0   7100.0
42   Honda  Black       200490.0        4.0   6337.0
43  Toyota   Blue       141617.0        4.0  19085.0
44  Toyota   Blue       213893.0        4.0   5743.0
45  Nissan   Blue       231057.0        4.0   5925.0
46  Toyota  White       100938.0        4.0  25196.0
47  Toyota   Blue       243969.0        4.0  16138.0
48  Nissan  White       107096.0        3.0   6075.0

In [17]:
## Data aggregating And Grouping
df.head()

     Make Colour  Odometer (KM) numb_doors    Price
0   Honda  White        35431.0        4.0  15323.0
1     BMW   Blue       192714.0        5.0  19943.0
2   Honda  White        84714.0        4.0  28343.0
3  Toyota  White       154365.0        4.0  13434.0
4  Nissan   Blue       181577.0        3.0  14043.0

In [18]:
grouped_mean = df.groupby('Colour')['Odometer (KM)'].mean()
print(grouped_mean)

Colour
Black    200490.000000
Blue     158447.947368
Green     98679.800000
Red       69697.000000
White    125958.333333
Name: Odometer (KM), dtype: float64

In [21]:
## if want to groupby with two categorial variables
grouped_mean = df.groupby(['Make','Colour'])['Price'].sum()
print(grouped_mean)

Make    Colour
BMW     Blue       19943.0
        White      17177.0
Honda   Black       6337.0
        Blue      101843.0
        Green      32226.0
        Red        23883.0
        White      83451.0
Nissan  Blue       82569.0
        Green      15940.0
        White      72813.0
Toyota  Blue       72829.0
        Green       6574.0
        Red        34465.0
        White      81571.0
Name: Price, dtype: float64

In [22]:
## we can also calculate mean
df.groupby(['Make','Colour'])['Price'].mean()

Make    Colour
BMW     Blue      19943.000000
        White     17177.000000
Honda   Black      6337.000000
        Blue      16973.833333
        Green     16113.000000
        Red       23883.000000
        White     16690.200000
Nissan  Blue      13761.500000
        Green      7970.000000
        White     12135.500000
Toyota  Blue      12138.166667
        Green      6574.000000
        Red       34465.000000
        White     16314.200000
Name: Price, dtype: float64

In [26]:
## Aggregate multiple Functions
grouped_agg = df.groupby(['Make'])['Price'].agg(['mean','sum','count'])
print(grouped_agg)

                mean       sum  count
Make
BMW     18560.000000   37120.0      2
Honda   17337.062500  277393.0     16
Nissan  12237.285714  171322.0     14
Toyota  15683.500000  219569.0     14

In [36]:
## Merging And Joining Dataframes
# create sample Dataframes

df1= pd.DataFrame({'Key': ['A','B','C'], 'Value': [1,2,3]})
df2= pd.DataFrame({'Key': ['A','B','D'], 'Value': [4,5,6]})

In [37]:
df1

  Key  Value
0   A      1
1   B      2
2   C      3

In [38]:
df2

  Key  Value
0   A      4
1   B      5
2   D      6

In [ ]:
## Merge Dataframe on the 'Key Columns'
pd.merge(df1,df2,on="Key",how="inner")  ## on means which column and how means how should happen

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

In [40]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [ ]:
pd.merge(df1,df2,on="Key",how="left")
# Left Merge = All rows from df1 + matching rows from df2
#No match → NaN

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [ ]:
pd.merge(df1,df2,on="Key",how="right")
# Keep all rows from the RIGHT DataFrame (df2)
#👉 Match rows from the left DataFrame (df1)
#👉 If a key from df2 is NOT found in df1 → fill with NaN

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6