In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\hp\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\roaming\python\python312\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\roaming\python\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

### Pandas - DataFrame And Series

pandas is a powerful data manipulation library in python , widely used for data analysis and data cleaning. it provides two primary data structures: Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes(rows and columns)

In [2]:
import pandas as pd

In [10]:
##Series
## A pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to column in a table 
## it is default...
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series /n", series)

Series /n 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## Create a Series From dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
## we can give different index according to requirement..

data = [10,20,30]
index = ['A','B','C']
pd.Series(data,index= index)

A    10
B    20
C    30
dtype: int64

In [19]:
## Dataframe
## create a dataframe from a dictionary of list

data = {
    'Name':['Nitish','Priyansu','Aniket'],
    'Age':[20,21,19],
    'City':['Banglore','New York','Florida']
}
df= pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age      City
0    Nitish   20  Banglore
1  Priyansu   21  New York
2    Aniket   19   Florida
<class 'pandas.core.frame.DataFrame'>

In [11]:
## Create a Data frame from a list of dictionaries..

data=[
    {'Name':'Nitish','Age':20,'City':'Dehradun'},
    {'Name':'Priyanshu','Age':21,'City':'Dehradun'},
    {'Name':'Aniket','Age':19,'City':'Dehradun'},
    {'Name':'Dipesh','Age':20,'City':'Dehradun'}

]
df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age      City
0     Nitish   20  Dehradun
1  Priyanshu   21  Dehradun
2     Aniket   19  Dehradun
3     Dipesh   20  Dehradun
<class 'pandas.core.frame.DataFrame'>

In [16]:
df = pd.read_csv('customer_data.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [17]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [21]:
## Accessing data from DataFrame
df

       Name  Age      City
0    Nitish   20  Banglore
1  Priyansu   21  New York
2    Aniket   19   Florida

In [22]:
df['Name']

0      Nitish
1    Priyansu
2      Aniket
Name: Name, dtype: object

In [ ]:
##another way to access 
## location
df.loc[0]

Name      Nitish
Age           20
City    Banglore
Name: 0, dtype: object

In [ ]:
## Accessing column index
##  index location
df.iloc[0]

Name      Nitish
Age           20
City    Banglore
Name: 0, dtype: object

In [29]:
## Accessing one element from data
df.iloc[0][1]

C:\Users\HP\AppData\Local\Temp\ipykernel_27276\2276566520.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

np.int64(20)

In [30]:
df

       Name  Age      City
0    Nitish   20  Banglore
1  Priyansu   21  New York
2    Aniket   19   Florida

In [31]:
## Accessing specified element 
df.at[1,'Age']

np.int64(21)

In [32]:
## Accessing specified element using iat means element of rows and column in data
df.iat[2,2]

'Florida'

In [ ]:
## Data Manipulation with Dataframe means adding something new..
df

       Name  Age      City
0    Nitish   20  Banglore
1  Priyansu   21  New York
2    Aniket   19   Florida

In [35]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

       Name  Age      City  Salary
0    Nitish   20  Banglore   50000
1  Priyansu   21  New York   60000
2    Aniket   19   Florida   70000

In [37]:
## Remove a column - checking rows wise
df.drop('Salary',axis=1,inplace=True)

In [38]:
df

       Name  Age      City
0    Nitish   20  Banglore
1  Priyansu   21  New York
2    Aniket   19   Florida

In [39]:
## Add age to the column
df['Age']=df['Age']+1
df

       Name  Age      City
0    Nitish   21  Banglore
1  Priyansu   22  New York
2    Aniket   20   Florida

In [40]:
## remove
df.drop(0,inplace=True)
df

       Name  Age      City
1  Priyansu   22  New York
2    Aniket   20   Florida

In [42]:
df = pd.read_csv('customer_data.csv')
print(df.head(5))

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter
1      2  1Ef7b82A4CAAD10    Preston    Lozano
2      3  6F94879bDAfE5a6        Roy     Berry
3      4  5Cef8BFA16c5e3c      Linda     Olsen
4      5  053d585Ab6b3159     Joanna    Bender

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan         Bensonview
4         Martin, Lang and Andrade     West Priscilla

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/

In [45]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

#Describe the Dataframe
print("Statistical summary:\n", df.describe())

Data types:
 Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object
Statistical summary:
             Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [46]:
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000